`timescale 1ns / 1ps

module tb_cache;

    // -------------------------------------------------------------------------
    // 1. Parameters & Signals
    // -------------------------------------------------------------------------
    parameter CLK_PERIOD = 10; // 100 MHz
    
    // DUT Signals (Must match the Verilog generated by Chisel)
    logic        clock;
    logic        reset;
    
    // CPU Interface
    logic [17:0] io_cpu_addr;
    logic [31:0] io_cpu_wrData;
    logic [3:0]  io_cpu_wrMask;
    logic        io_cpu_wrEn;
    logic        io_cpu_reqValid;
    wire  [31:0] io_cpu_rdData;
    wire         io_cpu_respValid;
    wire         io_cpu_stall;
    
    // Memory Interface
    wire  [17:0] io_mem_addr;
    wire         io_mem_rdEn;
    logic [31:0] io_mem_data;
    logic        io_mem_valid;
    logic        io_mem_ready;
    wire         io_mem_wrEn;
    wire  [31:0] io_mem_wrData;
    
    logic        io_invalidate;

    // Simulation Variables
    logic [31:0] main_memory [0:262143]; // 1MB Mock RAM
    integer i;

    // -------------------------------------------------------------------------
    // 2. DUT Instantiation
    // -------------------------------------------------------------------------
    // Replace 'FourWaySetAssociativeCache' with the exact module name from your .v file
    FourWaySetAssociativeCache dut (
        .clock            (clock),
        .reset            (reset),
        
        .io_cpu_addr      (io_cpu_addr),
        .io_cpu_wrData    (io_cpu_wrData),
        .io_cpu_wrMask    (io_cpu_wrMask),
        .io_cpu_wrEn      (io_cpu_wrEn),
        .io_cpu_reqValid  (io_cpu_reqValid),
        .io_cpu_rdData    (io_cpu_rdData),
        .io_cpu_respValid (io_cpu_respValid),
        .io_cpu_stall     (io_cpu_stall),
        
        .io_mem_addr      (io_mem_addr),
        .io_mem_rdEn      (io_mem_rdEn),
        .io_mem_data      (io_mem_data),
        .io_mem_valid     (io_mem_valid),
        .io_mem_ready     (io_mem_ready),
        .io_mem_wrEn      (io_mem_wrEn),
        .io_mem_wrData    (io_mem_wrData),
        
        .io_invalidate    (io_invalidate)
    );

    // -------------------------------------------------------------------------
    // 3. Clock & Reset Generation
    // -------------------------------------------------------------------------
    initial begin
        clock = 0;
        forever #(CLK_PERIOD/2) clock = ~clock;
    end

    // -------------------------------------------------------------------------
    // 4. Mock Main Memory Controller (The "Environment")
    // -------------------------------------------------------------------------
    // This logic simulates the latency and burst behavior of the BRAM/DDR
    
    always @(posedge clock) begin
        if (reset) begin
            io_mem_valid <= 0;
            io_mem_ready <= 0;
            io_mem_data  <= 0;
        end else begin
            // Default state
            io_mem_ready <= 0;
            io_mem_valid <= 0;

            // --- Handle Write-Through ---
            if (io_mem_wrEn) begin
                $display("[%0t] MEM_WRITE: Addr=0x%h Data=0x%h", $time, io_mem_addr, io_mem_wrData);
                main_memory[io_mem_addr] <= io_mem_wrData;
            end

            // --- Handle Read Refill (Burst) ---
            if (io_mem_rdEn) begin
                $display("[%0t] MEM_READ_REQ: Addr=0x%h (Refilling Cache Line)", $time, io_mem_addr);
                
                // Simulate Memory Latency (e.g., 2 cycles)
                repeat(2) @(posedge clock); 
                
                // Handshake: Ready to send data
                io_mem_ready <= 1; 
                @(posedge clock);
                io_mem_ready <= 0;

                // Send Burst (8 words for 32 bytes)
                // Note: Your Chisel code expects 8 beats
                for (int k = 0; k < 8; k++) begin
                    io_mem_valid <= 1;
                    io_mem_data  <= main_memory[io_mem_addr[17:0] + k]; // Simple linear burst
                    @(posedge clock);
                end
                
                io_mem_valid <= 0;
                $display("[%0t] MEM_READ_DONE: Burst Complete", $time);
            end
        end
    end

    // -------------------------------------------------------------------------
    // 5. Test Stimulus
    // -------------------------------------------------------------------------
    initial begin
        // Initialize Signals
        reset = 1;
        io_cpu_reqValid = 0;
        io_cpu_wrEn = 0;
        io_cpu_addr = 0;
        io_cpu_wrData = 0;
        io_cpu_wrMask = 0;
        io_invalidate = 0;

        // Initialize Mock Memory with some known pattern
        for (i = 0; i < 262143; i++) begin
            main_memory[i] = i; // Addr 0x5 has data 0x5, etc.
        end

        // Wait for Reset
        repeat(10) @(posedge clock);
        reset = 0;
        @(posedge clock);

        // =========================================================
        // TEST CASE 1: Read Miss (Compulsory Miss)
        // =========================================================
        $display("\n--- TC1: Read Miss @ 0x100 ---");
        // Expect: Stall -> Mem Read -> Refill -> Valid Data
        
        cpu_read(18'h100); 

        // =========================================================
        // TEST CASE 2: Read Hit 
        // =========================================================
        $display("\n--- TC2: Read Hit @ 0x100 (Should be fast) ---");
        // Expect: No stall, No Mem access
        
        cpu_read(18'h100);

        // =========================================================
        // TEST CASE 3: Read Hit (Same Block, Different Word)
        // =========================================================
        $display("\n--- TC3: Read Hit @ 0x101 (Same Cache Line) ---");
        
        cpu_read(18'h101);

        // =========================================================
        // TEST CASE 4: Write Through
        // =========================================================
        $display("\n--- TC4: Write @ 0x100 ---");
        // Expect: Cache Update AND Memory Write signal
        
        cpu_write(18'h100, 32'hDEADBEEF, 4'b1111);
        
        // Verify Read Back
        $display("\n--- TC5: Read Back @ 0x100 (Verify Write) ---");
        cpu_read(18'h100);

        // =========================================================
        // TEST CASE 5: Conflict Miss (Force Eviction)
        // =========================================================
        // Assuming 4 ways. We read 5 different addresses mapping to the same set (Index).
        // Set Index bits depend on your params. 
        // 64KB cache, 32B block -> 2048 blocks / 4 ways = 512 sets.
        // Index bits = log2(512) = 9 bits. Offset = 5 bits.
        // Addresses 0x0000, 0x4000, 0x8000, 0xC000, 0x10000 map to same set index 0.
        
        $display("\n--- TC6: Thrashing (Fill Ways 0-3) ---");
        cpu_read(18'h04000);
        cpu_read(18'h08000);
        cpu_read(18'h0C000);
        cpu_read(18'h10000); // 5th read, should evict one
		cpu_read(18'h14000);
        
        $display("\n--- TEST COMPLETE ---");
        $finish;
    end

    // -------------------------------------------------------------------------
    // Tasks for easier driving
    // -------------------------------------------------------------------------
    task cpu_read(input [17:0] addr);
        begin
            @(posedge clock);
            io_cpu_addr     <= addr;
            io_cpu_wrEn     <= 0;
            io_cpu_reqValid <= 1;

            // Wait for Stall to de-assert if it goes high
            do begin
                @(posedge clock);
            end while (io_cpu_stall);

            // Wait for valid response
            while (!io_cpu_respValid) @(posedge clock);
            
            $display("CPU Read: Addr=0x%h Data=0x%h", addr, io_cpu_rdData);
            
            io_cpu_reqValid <= 0;
            @(posedge clock);
        end
    endtask

    task cpu_write(input [17:0] addr, input [31:0] data, input [3:0] mask);
        begin
            @(posedge clock);
            io_cpu_addr     <= addr;
            io_cpu_wrData   <= data;
            io_cpu_wrMask   <= mask;
            io_cpu_wrEn     <= 1;
            io_cpu_reqValid <= 1;

            // Wait for Stall
            do begin
                @(posedge clock);
            end while (io_cpu_stall);
            
            // Check if write-through happened
            // (In a real testbench, you'd use assertions here)
            
            io_cpu_reqValid <= 0;
            io_cpu_wrEn     <= 0;
            @(posedge clock);
        end
    endtask

endmodule